# Generated by Django 3.2 on 2023-04-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='customer_review',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
